
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Geral
 */
public class Exemplo8_11 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo8_11
     */
    public Exemplo8_11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCbxMensagens = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exemplo 11");

        jCbxMensagens.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCbxMensagens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pergunta", "Informação", "Alerta", "Erro", "Definida pelo Usuario", "Somente Mensagem" }));
        jCbxMensagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxMensagensActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jCbxMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jCbxMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCbxMensagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxMensagensActionPerformed
        switch (jCbxMensagens.getSelectedIndex()) {
            case 0:
            JOptionPane.showMessageDialog(null, "Estou aprendendo Java", "Pergunta",JOptionPane.QUESTION_MESSAGE);
            break;
            
            case 1:
            JOptionPane.showMessageDialog(null, "Gravação OK", "Informação",JOptionPane.INFORMATION_MESSAGE);
            break;
            
            case 2:
            JOptionPane.showMessageDialog(null, "Cuidado!!!", "Alerta",JOptionPane.WARNING_MESSAGE);
            break;
            
            case 3:
            JOptionPane.showMessageDialog(null, "Erro", "Erro",JOptionPane.ERROR_MESSAGE);
            break;
            
            case 4:
            JOptionPane.showMessageDialog(null, "Deixa o Like Lá na Moralzinha!", "SILVA",JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon("src/Imagens/Gaules Rebaixado.gif"));
            break;
            
            case 5:
            JOptionPane.showMessageDialog(null, "Meteu Essa!?", "Mensagem",JOptionPane.PLAIN_MESSAGE);
            break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jCbxMensagensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo8_11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCbxMensagens;
    // End of variables declaration//GEN-END:variables
}
