
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Geral
 */
public class Exemplo8_4 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo8_4
     */
    public Exemplo8_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIngles = new javax.swing.JCheckBox();
        jInfo = new javax.swing.JCheckBox();
        jVerificar = new javax.swing.JButton();
        jMarcar = new javax.swing.JButton();
        jDesmarcar = new javax.swing.JButton();
        jGau = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exemplo 4");

        jIngles.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jIngles.setText("Inglês");
        jIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInglesActionPerformed(evt);
            }
        });

        jInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jInfo.setText("Informática");

        jVerificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jVerificar.setText("Verificar");
        jVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVerificarActionPerformed(evt);
            }
        });

        jMarcar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jMarcar.setText("Marcar");
        jMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMarcarActionPerformed(evt);
            }
        });

        jDesmarcar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jDesmarcar.setText("Desmarcar");
        jDesmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDesmarcarActionPerformed(evt);
            }
        });

        jGau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gaules Rebaixado.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGau, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesmarcar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMarcar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jGau, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jIngles)
                        .addGap(18, 18, 18)
                        .addComponent(jInfo)
                        .addGap(27, 27, 27)
                        .addComponent(jVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMarcar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesmarcar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInglesActionPerformed

    private void jMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMarcarActionPerformed
        jInfo.setSelected(true);
        jIngles.setSelected(true);
    }//GEN-LAST:event_jMarcarActionPerformed

    private void jDesmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDesmarcarActionPerformed
        jInfo.setSelected(false);
        jIngles.setSelected(false);
    }//GEN-LAST:event_jDesmarcarActionPerformed

    private void jVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVerificarActionPerformed
        String selecao = "Selecionados: ";
                if(jIngles.isSelected()){
                    selecao += "\nInglês";
                }
                if(jInfo.isSelected()){
                    selecao += "\nInformática";
                }
                
                if(!jIngles.isSelected() && !jInfo.isSelected()){
                    JOptionPane.showMessageDialog(null, "Nenhum Curso Selecionado!!!");
                }else{
                    JOptionPane.showMessageDialog(null, selecao);
                }
    }//GEN-LAST:event_jVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo8_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo8_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDesmarcar;
    private javax.swing.JButton jGau;
    private javax.swing.JCheckBox jInfo;
    private javax.swing.JCheckBox jIngles;
    private javax.swing.JButton jMarcar;
    private javax.swing.JButton jVerificar;
    // End of variables declaration//GEN-END:variables
}
